something = input('Type something: ')

print('The value of type {} is:'.format(type(something)))
print('Alphanumeric: ', something.isalnum())
print('Alphabetic: ', something.isalpha())
print('Decimal: ', something.isdecimal())
print('Digit: ', something.isdigit())
print('Identifier: ', something.isidentifier())
print('Lower: ', something.islower())
print('Upper: ', something.isupper())
print('Numeric: ', something.isnumeric())
print('Printable: ', something.isprintable())
print('Space: ', something.isspace())
print('Title: ', something.istitle())
